<div id="main">
            <div class="maincontent">
                  <?php
               if(isset($_GET['quanly'])){
                  $tam=$_GET['quanly'];
               }else{
                  $tam='';
               }
               if($tam=='camon'){
                  include("main/camon.php");
               }
               elseif($tam=='dangky'){
                  include("main/dangky.php");
               }
               elseif($tam=='dangnhap'){
                  include("main/dangnhap.php");
               }
               elseif($tam=='danhmucsanpham'){
                  include("main/danhmuc.php");
               }
               elseif($tam=='giohang'){
                  include("main/giohang.php");
               }
               elseif($tam=='tintuc'){
                  include("main/tintuc.php");
               }
               elseif($tam=='lienhe'){
                  include("main/lienhe.php");
               }
               elseif($tam=='sanpham'){
                  include("main/sanpham.php");
               }
               else{
                  include("main/trangchu.php"); 
               }
               
               ?>
			</div>
</div>